language: go

go:
- 1.12
env:
  - GO111MODULE=on
script:
  - go build .

before_deploy:
  - git config --local user.name "${GIT_USER_NAME}"
  - git config --local user.email "${GIT_USER_EMAIL}"
  - git tag

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "wwcdocker"
  skip_cleanup: true
  on:
    tags: true